import type { Metadata } from "next";
import {DM_Sans } from "next/font/google";
import "./globals.css";

const dmtSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmtSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
